eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
        serviceUrl:
            defaultZone: http://peer4.com:8182/eureka
    instance:
        hostname: peer3.com
        prefer-ip-address: false
hello-service:
    ribbon:
        ConnectTimeout: 250
        MaxAutoRetries: 1
        MaxAutoRetriesNextServer: 2
        OkToRetryOnAllOperations: true
        ReadTimeout: l000
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutinMilliseconds: l0000
management:
    endpoint:
        health:
            show-details: always
    endpoints:
        web:
            base-path: /monitor
            exposure:
                include: '*'
spring:
    application:
        name: peer3.com
    cloud:
        loadbalancer:
            retry:
                enabled: true
