eureka:
    client:
        fetch-registry: true
        register-with-eureka: true
hello-service:
    ribbon:
        ConnectTimeout: 250
        MaxAutoRetries: 1
        MaxAutoRetriesNextServer: 2
        OkToRetryOnAllOperations: true
        ReadTimeout: l000
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutinMilliseconds: l0000
ribbon:
    ConnectTimeout: 10000
    ReadTimeout: 10000
spring:
    cloud:
        loadbalancer:
            retry:
                enabled: true
