stages:          # List of stages for jobs, and their order of execution
  - build
  #- deploy
build-job-master:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - cd
  script:
    - echo "mvn clean -U package and  docker build image to harbor "\
    -  echo `date +%F-%H-%M-%S`  > image_tag
    - cd com.unknow.first.common/
    - /opt/apache-maven-3.8.1/bin/mvn clean  deploy package -Dmaven.test.skip=true
    - cd ..
    - cd springcloud-tester
    - /opt/apache-maven-3.8.1/bin/mvn clean  deploy package -Dmaven.test.skip=true
    - cd  springcloud-gateway-tester/
    - docker build -t app.lianziyou.tech:5000/framework/spring-gateway:`cat ../../image_tag` .
    - docker tag  app.lianziyou.tech:5000/framework/spring-gateway:`cat ../../image_tag` app.lianziyou.tech:5000/framework/spring-gateway:latest
    - docker push app.lianziyou.tech:5000/framework/spring-gateway:latest
    - cd ..
    - cd  com.longyou.commservice/
    - docker build -t app.lianziyou.tech:5000/framework/commonservice:`cat ../../image_tag` .
    - docker tag  app.lianziyou.tech:5000/framework/commonservice:`cat ../../image_tag` app.lianziyou.tech:5000/framework/commonservice:latest
    - docker push app.lianziyou.tech:5000/framework/commonservice:latest
    - echo "Compile complete."
  only:
    - master

build-job-dev:       # This job runs in the build stage, which runs first.
  stage: build
  tags:
    - cd
  script:
    - echo "mvn clean -U package and  docker build image to harbor "\
    -  echo `date +%F-%H-%M-%S`  > image_tag
    - cd com.unknow.first.common/
    - /opt/apache-maven-3.8.1/bin/mvn clean   package -Dmaven.test.skip=true
    - cd ..
    - cd springcloud-tester
    - /opt/apache-maven-3.8.1/bin/mvn clean   package -Dmaven.test.skip=true
    - cd  springcloud-gateway-tester/
    - docker build -t app.lianziyou.tech:5000/framework/spring-gateway_dev:`cat ../../image_tag` .
    - docker tag  app.lianziyou.tech:5000/framework/spring-gateway_dev:`cat ../../image_tag` app.lianziyou.tech:5000/framework/spring-gateway_dev:latest
    - docker push app.lianziyou.tech:5000/framework/spring-gateway_dev:latest
    - cd ..
    - cd  com.longyou.commservice/
    - docker build -t app.lianziyou.tech:5000/framework/commonservice_dev:`cat ../../image_tag` .
    - docker tag  app.lianziyou.tech:5000/framework/commonservice_dev:`cat ../../image_tag` app.lianziyou.tech:5000/framework/commonservice_dev:latest
    - docker push app.lianziyou.tech:5000/framework/commonservice_dev:latest
    - echo "Compile complete."
  only:
    - dev
