logging:
  level:
    com.longyou.gateway: DEBUG
    org.springframework.web.servlet.mvc.method: INFO
    org.springframework.web.server.adapter: INFO
    org.springframework.web: INFO
gateway:
  discovery:
    locator:
      enabled: true
system:
  email:
    enable: true
  auth_basic_expire_time: 18000000
  route:
    cors:
      allow-headers: x-requested-with,authorization,Content-Type,Authorization,credential,X-XSRF-TOKEN,token,username,client,microAppindex,userType,x-header-mfa-value
      #      allow-headers: "*"
      allow-methods: "*"
      allow-orgins: "*"
      allow-expose: "*"
      max-age: 1800L
  static:
    web-uploadpath: E:/work/workspace/web/
  userinfo:
    query_user_url: http://${spring.application.group:}COMMON-SERVICE/userinfo/getUserByName
    get_url: http://${spring.application.group:}SPRING-GATEWAY/user/info/authentication
redis:
  host: localhost
  port: 6379
  database: 1
  lettuce:
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1ms
      min-idle: 1
management:
  endpoint:
    gateway:
      enabled: true # default value
  endpoints:
    web:
      exposure:
        include: gateway
spring:
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
  data:
    mongodb:
      option:
        server-selection-timeout: 10000
swagger:
  WebMvcEndpoint:
    enabled: false