gateway:
  discovery:
    locator:
      enabled: true
spring:
  cloud:
    gateway:
      routes:
        - id: framework
          uri: http://localhost:20040/framework,http://localhost:20050/framework
          predicates:
            - Path=/framework/**
      discovery:
        locator:
          enabled: true   #直接从配置中心获取应用并转发
management:
  security:
    enabled: false
redis:
  host: localhost
  port: 6379
  database: 1
  lettuce:
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1ms
      min-idle: 1