gateway:
  discovery:
    locator:
      enabled: true
spring:
  cloud:
    gateway:
      routes:
        - id: framework
          uri: http://localhost:20040/framework,http://localhost:20050/framework
          predicates:
            - Path=/framework/**
      discovery:
        locator:
          enabled: true   #直接从配置中心获取应用并转发
  management:
    security:
      enabled: false
  resources:
    static-locations: classpath:/META-INF/resources/,classpath:/resources/,\
                      classpath:/static/,classpath:/public/,file:${system.static.web-uploadpath}
system:
  auth_basic_expire_time: 18000000
  route:
    cors:
      allow-headers: x-requested-with, authorization, Content-Type, Authorization, credential, X-XSRF-TOKEN,token,username,client
#      allow-headers: "*"
      allow-methods: "*"
      allow-orgins: "*"
      allow-expose: "*"
      max-age: 1800L
  static:
    web-uploadpath: E:/work/workspace/web/
redis:
  host: localhost
  port: 6379
  database: 1
  lettuce:
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1ms
      min-idle: 1