logging:
  level:
    com:
      longyou:
        gateway: DEBUG
gateway:
  discovery:
    locator:
      enabled: true
system:
  auth_basic_expire_time: 18000000
  route:
    cors:
      allow-headers: x-requested-with, authorization, Content-Type, Authorization, credential, X-XSRF-TOKEN,token,username,client,microAppindex,userType
      #      allow-headers: "*"
      allow-methods: "*"
      allow-orgins: "*"
      allow-expose: "*"
      max-age: 1800L
  static:
    web-uploadpath: E:/work/workspace/web/
  userinfo:
    query_user_url: http://${spring.application.group:}COMMON-SERVICE/userinfo/getUserByName
    get_url: http://${spring.application.group:}SPRING-GATEWAY/user/info/authentication
redis:
  host: localhost
  port: 6379
  database: 1
  lettuce:
    pool:
      max-active: 8
      max-idle: 8
      max-wait: -1ms
      min-idle: 1
management:
  endpoint:
    gateway:
      enabled: true # default value
  endpoints:
    web:
      exposure:
        include: gateway