system:
  current_appname: 支付中心服务
spring:
  rabbitmq:
    addresses: 192.168.10.14:5692,192.168.10.14:5683,192.168.10.14:5684
    username: payCenter
    password: payCenter
    virtual-host: payCenter