eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    healthcheck:
      enabled: true
  instance:
    health-check-url-path: /monitor/health
ribbon:
  ConnectTimeout: 60000
  MaxAutoRetries: 1
  MaxAutoRetriesNextServer: 2
  OkToRetryOnAllOperations: true
  ReadTimeout: 60000
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutinMilliseconds: l0000
spring:
  cloud:
    loadbalancer:
      retry:
        enabled: true
