spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/longyou/springcloud-config
          search-paths: ${sys.config_path:tester}
          username: 18028750128@126.com
          password: sskxttkl11

#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: https://gitee.com/longyou/springcloud-config
#          search-paths: ${sys.config_path:htcloud}
#          username: 18028750128@126.com
#          password: sskxttkl11

#spring:
#  cloud:
#    config:
#      server:
#        git:
#          uri: http://office-dev03.ly-huangtu.cn:10001/dev_group/config.git # 配置git仓库的地址
#          search-paths: ${sys.config_path:htcloud}  #git仓库地址下的相对地址，可以配置多个，用,分割。
#          username: htconfig  #账号密码写真实的快一些我觉得，不使用也能访问有点慢
#          password: htconfig123