spring:
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/longyou/springcloud-config
          search-paths: ${sys.config_path:tester}
          username: 18028750128@126.com
          password: sskxttkl11
