system:
  current_appname: 通用服务
logging:
  level:
    com:
      longyou:
        common: INFO
spring:
  datasource:
    url: jdbc:mysql://${local-server.ip}:10002/framework${local-server.suffix}?userSSL=false&autoReconnect=true&failOverReadOnly=false&useUnicode=true&characterEncoding=UTF8&serverTimezone=GMT%2B8&zeroDateTimeBehavior=CONVERT_TO_NULL
    username: root
    password: 1qaz@WSX
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    max-active: 200
    max-idle: 100
    min-idle: 50
    initial-size: 10
    maximum-pool-size: 100