eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka,http://localhost:8082/eureka
management:
  security:
    enabled: false
logging:
  level:
    org:
      springcloud:
        eureka:
          client:
            tester: DEBUG
      hibernate: ERROR
      springframework:
        web: DEBUG
    com:
      longyou:
        springcloud: DEBUG
    root: INFO
