<project xmlns="http://maven.apache.org/POM/4.0.0"
  xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
  xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/maven-v4_0_0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.unknow.first</groupId>
    <artifactId>common-parent</artifactId>
    <version>0.0.3-SNAPSHOT</version>
  </parent>
  <groupId>com.lianziyou</groupId>
  <artifactId>twitter-app</artifactId>
  <name>Archetype - twitter-app</name>
  <url>http://maven.apache.org</url>
  <dependencies>
    <dependency>
      <groupId>oauth.signpost</groupId>
      <artifactId>signpost-core</artifactId>
      <version>1.2.1.2</version>
    </dependency>

    <dependency>
      <groupId>oauth.signpost</groupId>
      <artifactId>signpost-commonshttp4</artifactId>
      <version>1.2.1.2</version>
    </dependency>

    <dependency>
      <groupId>com.twitter</groupId>
      <artifactId>twitter-api-java-sdk</artifactId>
      <version>1.1.4</version>
    </dependency>
  </dependencies>
</project>
