logging:
  level:
    com:
      longyou:
        common: DEBUG
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params:
system:
  userinfo:
    get_url: http://${spring.application.group:}SPRING-GATEWAY/user/info/authentication
  config:
    excludedAuthPages: /userinfo/getUserByName
  api:
    inner:
      url-patterns: "/inner/*,/userinfo/getUserByName" #仅内部调用的api接口