logging:
  level:
    com:
      longyou:
        common: DEBUG
pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params:
system:
  redisson:
    enabled: false #如果要放开redisson,那么改成true，暂时只支持主从模式
    master-slave-config:
      password: 1qaz@WSX
      master-address: redis://192.168.74.128:10004
      slave-addresses:
        - redis://192.168.74.128:10005
      connect-timeout: 5000
  userinfo:
    get_url: http://${spring.application.group:}SPRING-GATEWAY/user/info/authentication
  config:
    excludedAuthPages: /userinfo/getUserByName
  api:
    inner:
      url-patterns: "/inner/*,/userinfo/getUserByName" #仅内部调用的api接口